baseURL: "https://yatharthb97.github.io/"
#baseURL: http://localhost:1313/

title: Yatharth Bhasin
pagination.pagerSize: 10
theme: "hugo-PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-178533000-1

minify:
  disableXML: true
  minifyOutput: false

params:
  enableInlineShortcodes: true
  social: true

  mainSections:
    - blog
    - gallery
    - projects
    - publications
    - "Biology🧬 + Physics🔭"

  custom_css : 
    - "css/rel_image.css"
    - "/css/timeline.css"
    - "/css/blink_text.css"
    - "/css/textflips.css"
    - "/css/marquee.css"
  #  - "/css/boxmarquee.css"

  # Default Recommended ↓

  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Yatharth Bhasin
  description: "Hello 👋! I am Yatharth and I am a scientist. Find out about me and my work by visiting my website."
  keywords: [Blog, Portfolio, PaperMod, Yatharth, Bhasin]
  author: "Yatharth Bhasin"
  # author: ["Me", "You"] # multiple authors
  images: ["website_tile.svg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  linkFullImages: true
  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: false
    favicon: "/images/website_tile.svg"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Yatharth Bhasin"
    icon: "/images/header_button.gif"
    iconHeight: 30

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Yatharth Bhasin
    subtitle: "PhD student mixing Physics, Biology, and Computers in a test tube.<br>I build microscopes to study how cells swim."
    imageUrl: "/images/life_of_a_cell.gif"
    imageWidth: 250
    imageHeight: 250
    linkFullImages: true
    imageTitle: YB
    buttons:
      - name: Trappy-Scopes 🔬
        url: /projects/trappyscopes/
      - name: About Me 👋
        url: /aboutme/
      - name: Collaborate! ☭
        url: /collaborate/
#      - name: Blog 📝
#        url: blog
#      - name : Projects 🔭
#        url: /projects/
#      - name : "Resume 🎓"
#        url: https://drive.google.com/file/d/1XtsUeojuXNe-d_a9AhDXsk7MJZiTlsvz/view?usp=sharing
      - name : Code 👨‍💻
        url: https://github.com/yatharthb97
      - name : Web Archive ⌛
        url: /archives/
      - name : Tags 🏷️
        url: /tags/
#      - name : Categories 📂
#        url : /categories/


  # home-info mode
  homeInfoParams:
    Title: "Hi! I am Yatharth. \U0001F44B"
    Content: "Exploring hazzy recurrences in nature at the interface of Physics, Computation, and Biology. Soon starting my PhD journey."

  socialIcons:
    - name: github
      url: "https://github.com/yatharthb97"
    - name: bluesky
      url: "https://bsky.app/profile/yatharth1997.bsky.social"
    - name: instagram
      url: "https://www.instagram.com/anar_chy_problem/"
    - name : linkedin
      url : https://www.linkedin.com/in/yatharth1997/
    - name: email
      url: "mailto:yatharth1997+ws@gmail.com"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
    responsiveImages: false # Reduce generation time and size of the site, you can disable this feature
    linkFullImages: true

  editPost:
    URL: "https://github.com/yatharthb97/yatharthb97.github.io/tree/main/content/"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    #useExtendedSearch: true
    includeScore: true
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content", "tags", "author", "date", "description"]

menu:
  main:
    - identifier: projects
      name: projects
      url: /projects/
      weight: 1
      
    - identifier: blog
      name: blog
      url: /blog/
      weight : 2

    - identifier: publications
      name : publications
      url : /publications/
      weight : 3
    
    - identifier : search
      name : search
      url: /search/
      weight : 4
    
    - identifier: gallery
      name: gallery
      url: /gallery/
      weight : 5

    - identifier : about me
      name : about me
      url : /aboutme/
      weight : 1
    

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai


# Search
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for necessary


markup:
  goldmark:
    renderer:
      unsafe: true


imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: photo
  quality:    
  resampleFilter: Box